#! /bin/bash

## ---------------------------------------------------------------------------
## TRINITY 1 - KMER COUNTING
## Generate the k-mer catalog using Jellyfish
## Authors: Tracy Chew, Andrey Bliznyuk, Rika Kobayashi
## Suggested acknowledgement: "The authors acknowledge the scientific and/or technical 
## assistance of Tracy Chew of the Sydney Informatics Hub at the University of Sydney 
## and use of the National Computational Infrastructure facility."
## ---------------------------------------------------------------------------

module load samtools/1.9
module load java/jdk1.8.0_60
module load bowtie2/2.3.3.1
module load jellyfish/2.2.6
module load salmon/0.11.0
module load perl/5.22.1
module load trinity/2.8.4
module load python3/3.6.7
module load parallel/20190322

# Set trap
# EXIT runs on any exit, signalled or not.
finish(){
	echo "$(date) : Archiving trinity workdir/outdir and copying to /short"
	cd ${PBS_JOBFS}
	tar -cf ${out}/trinity_workdir_1.tar trinity_workdir
	tar -cf ${out}/trinity_outdir_1.tar trinity_outdir
	rm -rf ${TRINITY_WORKDIR}
	rm -rf ${TRINITY_OUTDIR}
	echo "$(date) : Finished archiving trinity_workdir_1 and trinity_outdir_1"
}
trap finish EXIT

# Set variables
first=$(awk -v taskID=${input} '$1==taskID {print $2}' ${list})
second=$(awk -v taskID=${input} '$1==taskID {print $3}' ${list})

echo "$(date) : Beginning trinity_1.pbs: KMER counting with Jellyfish"

# Create TEMP directory in JOBFS
export TRINITY_WORKDIR=${PBS_JOBFS}/trinity_workdir
mkdir -p ${TRINITY_WORKDIR}

# Create output directory in JOBFS
export TRINITY_OUTDIR=${PBS_JOBFS}/trinity_outdir
mkdir -p ${TRINITY_OUTDIR}

# Make output directory in short, later save tmpdir and outdir tars here
mkdir -p ${out}

# Move to jobfs for outdir
cd ${TRINITY_OUTDIR}

# Run trinity, stop after inchworm, do not run chrysalis
Trinity --seqType ${seqtype} \
	--max_memory ${mem} \
	--no_version_check \
	--left ${first} \
	--right ${second} \
	--no_normalize_reads \
	--CPU ${cpus} \
	--workdir ${TRINITY_WORKDIR} \
	--output ${tissue}_trinity_2.8.4 \
	--verbose \
	--no_run_inchworm

echo "$(date) : Finished trinity_1"